[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 88
order_by_type = true
length_sort = true
lines_between_types = 1
group_by_package = true
force_alphabetical_sort_within_sections = true
combine_straight_imports = false
balanced_wrapping = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "OPENBABEL", "PYMATGEN", "FIREWORKS", "CUSTODIAN", "MDPROPTOOLS", "FIRSTPARTY", "LOCALFOLDER"]
forced_separate = ["openbabel", "pymatgen", "fireworks", "custodian", "mdproptools", "mispr"]
known_openbabel = ["openbabel"]
known_pymatgen = ["pymatgen"]
known_fireworks = ["fireworks"]
known_custodian = ["custodian"]
known_mdproptools = ["mdproptools"]
known_mispr = ["mispr"]


[tool.black]
line-length = 88
